version: 2.1

orbs:
  ruby: circleci/ruby@1.8

jobs:
  test:
    parameters:
      ruby-version:
        type: string
      rails-version:
        type: string
      database:
        type: string
    docker:
      - image: ruby:<< parameters.ruby-version >>
      - image: cimg/postgres:14.1
      - image: cimg/mysql:8.0
    steps:
      - checkout
      - run:
          name: bundle update --no-ri --no-rdoc
          command: BUNDLE_GEMFILE=gemfiles/rails_<< parameters.rails-version >>.gemfile bundle update
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for Postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: rspec
          command: DB=<< parameters.database >> rspec spec

workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["3.0", "3.1", "3.2", "3.3", "4.0"]
              rails-version: ["6.0", "6.1", "7.0", "7.1", "7.2", "8.0", "8.1"]
              database: ["postgresql", "sqlite3", "mysql2"]
            exclude:
              # Rails 7.2 requires Ruby 3.1+
              - ruby-version: "3.0"
                rails-version: "7.2"
                database: "postgresql"
              - ruby-version: "3.0"
                rails-version: "7.2"
                database: "sqlite3"
              - ruby-version: "3.0"
                rails-version: "7.2"
                database: "mysql2"
              # Rails 8.0 requires Ruby 3.2+
              - ruby-version: "3.0"
                rails-version: "8.0"
                database: "postgresql"
              - ruby-version: "3.0"
                rails-version: "8.0"
                database: "sqlite3"
              - ruby-version: "3.0"
                rails-version: "8.0"
                database: "mysql2"
              - ruby-version: "3.1"
                rails-version: "8.0"
                database: "postgresql"
              - ruby-version: "3.1"
                rails-version: "8.0"
                database: "sqlite3"
              - ruby-version: "3.1"
                rails-version: "8.0"
                database: "mysql2"
              # Rails 8.1 requires Ruby 3.2+
              - ruby-version: "3.0"
                rails-version: "8.1"
                database: "postgresql"
              - ruby-version: "3.0"
                rails-version: "8.1"
                database: "sqlite3"
              - ruby-version: "3.0"
                rails-version: "8.1"
                database: "mysql2"
              - ruby-version: "3.1"
                rails-version: "8.1"
                database: "postgresql"
              - ruby-version: "3.1"
                rails-version: "8.1"
                database: "sqlite3"
              - ruby-version: "3.1"
                rails-version: "8.1"
                database: "mysql2"
              # Ruby 4.0 requires Rails 8.0+
              - ruby-version: "4.0"
                rails-version: "6.0"
                database: "postgresql"
              - ruby-version: "4.0"
                rails-version: "6.0"
                database: "sqlite3"
              - ruby-version: "4.0"
                rails-version: "6.0"
                database: "mysql2"
              - ruby-version: "4.0"
                rails-version: "6.1"
                database: "postgresql"
              - ruby-version: "4.0"
                rails-version: "6.1"
                database: "sqlite3"
              - ruby-version: "4.0"
                rails-version: "6.1"
                database: "mysql2"
              - ruby-version: "4.0"
                rails-version: "7.0"
                database: "postgresql"
              - ruby-version: "4.0"
                rails-version: "7.0"
                database: "sqlite3"
              - ruby-version: "4.0"
                rails-version: "7.0"
                database: "mysql2"
              - ruby-version: "4.0"
                rails-version: "7.1"
                database: "postgresql"
              - ruby-version: "4.0"
                rails-version: "7.1"
                database: "sqlite3"
              - ruby-version: "4.0"
                rails-version: "7.1"
                database: "mysql2"
              - ruby-version: "4.0"
                rails-version: "7.2"
                database: "postgresql"
              - ruby-version: "4.0"
                rails-version: "7.2"
                database: "sqlite3"
              - ruby-version: "4.0"
                rails-version: "7.2"
                database: "mysql2"
